# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: ranmusao396292_511@163.com
    password: XXFZDCESNEKZHAOH
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  #   文件上传的配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB

# 阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tShHvTghSGiteidgrZi
    accessKeySecret: wNufqd8fJNuu70d1nF5PR1QtAebBfx
    bucketName: xiao-shu-shu
    catalogueCover: Cover/
    catalogueAvatar: Avatar/
    catalogueBooks: Books/
    catalogueMaterial: Material/