spring:
  datasource:
    operator:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/operator
      username: root
      password: 5201314Eminem
#    books:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/books
#      username: root
#      password: 5201314Eminem
#    resources:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/resources
#      username: root
#      password: 5201314Eminem

